travis:
  secure:
    BINSTAR_TOKEN: EPbMWja2F3nVpPOVfwRIMLb4vVJbttrR5jHZnQ++saE7sOvUcETGi9d8m3YLp+mrRNP4hZ/VlX05e4yQdGdchW26+6FLJ7yDQ2koVryQKbh5Xrn0YzR92RvlfiXrHHsIxSxmpCELe14CNa4KPzKqYF0oAd2WGj4Akl2t7KcvE8OK8oSeyNxtZQ7PmeDXihokecborJtyWitLMSlXIi3NHaa4SMBk+QC0F2e11hanlMqnVpOw904C7LHs8jBSpVZKIdFmD2HaW8mh6xzjIXwfgxiUIeUbinuADtKuJW7JcDI/RlbgA91PCa5fJcNEKbc4nr1TK6C1P/BkHWRFS+cJLiVewKpQr+DUt+TFO17M7QOd4b5lMpSuaqAl5qp3elDv7+gwS431XCuzS+wD0TGUTfosbWnkV+B9QmUzComKjYcjw48OdHMpXedR14bWte4MdgDhKJgEY+DsJ6w2FvXkMLCm1C+qg+VzTv32hqG5x4sUf7kp4M30lJ2mtylRQ+WE6xOsW2WrUc1EeIIz7Obmk+1vMpyMqx/B/lTwSWCJ4OutNlPZEM+62wOk7lhQDkMFiykvXWb4eczRvCbLPYOM6DJzwbKz0i/dQg9j8BnzDt43aJnlOaipJIJzgx3lgZeE/K35T8s4I1DzOtUQTogDeA6LvkIps9XIMXdRHJzSf8k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
